spring.application.name=recipe-api

# Fix springdoc 2.8.x + Spring Boot 3.5 wildcard pattern bug
springdoc.swagger-ui.path=/swagger-ui.html

# DB config
# DB local Docker container
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Log pattern timestamp, level, thread, logger (class name), message
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n

# Verbose logging for local development
logging.level.root=INFO
logging.level.com.recime.recipeapi=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
logging.level.org.springframework.web=DEBUG
